package org.delegator.entities;

// Generated 11:12:45 09/08/2009 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WorksForId generated by hbm2java
 */
@Embeddable
public class WorksForId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int managerId;
	private int eid;

	public WorksForId() {
	}

	public WorksForId(int managerId, int eid) {
		this.managerId = managerId;
		this.eid = eid;
	}

	@Column(name = "ManagerId", nullable = false)
	public int getManagerId() {
		return this.managerId;
	}

	public void setManagerId(int managerId) {
		this.managerId = managerId;
	}

	@Column(name = "Eid", nullable = false)
	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorksForId))
			return false;
		WorksForId castOther = (WorksForId) other;

		return (this.getManagerId() == castOther.getManagerId())
				&& (this.getEid() == castOther.getEid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getManagerId();
		result = 37 * result + this.getEid();
		return result;
	}

}
