package src.com.delegator.entities;

// Generated 09:11:28 04/07/2010 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Divisions generated by hbm2java
 */
@Entity
@Table(name = "divisions", catalog = "delegator")
public class Divisions implements java.io.Serializable {

	private int divId;
	private Employee employee;
	private String name;
	private Set employees = new HashSet(0);
	private Set employees_1 = new HashSet(0);

	public Divisions() {
	}

	public Divisions(int divId, Employee employee, String name) {
		this.divId = divId;
		this.employee = employee;
		this.name = name;
	}

	public Divisions(int divId, Employee employee, String name, Set employees,
			Set employees_1) {
		this.divId = divId;
		this.employee = employee;
		this.name = name;
		this.employees = employees;
		this.employees_1 = employees_1;
	}

	@Id
	@Column(name = "DivId", unique = true, nullable = false)
	public int getDivId() {
		return this.divId;
	}

	public void setDivId(int divId) {
		this.divId = divId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ManagerId", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "div_worker", catalog = "delegator", joinColumns = { @JoinColumn(name = "DivId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Eid", nullable = false, updatable = false) })
	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "div_worker", catalog = "delegator", joinColumns = { @JoinColumn(name = "DivId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Eid", nullable = false, updatable = false) })
	public Set getEmployees_1() {
		return this.employees_1;
	}

	public void setEmployees_1(Set employees_1) {
		this.employees_1 = employees_1;
	}

}
