package src.com.delegator.entities;

// Generated 09:11:28 04/07/2010 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DoneById generated by hbm2java
 */
@Embeddable
public class DoneById implements java.io.Serializable {

	private int tid;
	private int eid;

	public DoneById() {
	}

	public DoneById(int tid, int eid) {
		this.tid = tid;
		this.eid = eid;
	}

	@Column(name = "Tid", nullable = false)
	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	@Column(name = "Eid", nullable = false)
	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DoneById))
			return false;
		DoneById castOther = (DoneById) other;

		return (this.getTid() == castOther.getTid())
				&& (this.getEid() == castOther.getEid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTid();
		result = 37 * result + this.getEid();
		return result;
	}

}
